### PR TITLE
fix: remove unnecessary validation blocking names with only one word

### PR DESCRIPTION
**Pull request by aleen42**

### CODE REVIEW

**Comment by CaptainLiao** [comment]
check pageckageName is necessary.

how about `const fileNameRE = /^[\w-.]*[\w]$/`?

**Comment by aleen42** [comment]
How about this? https://stackoverflow.com/a/11794507/5698182

**Comment by CaptainLiao** [comment]
> How about this? https://stackoverflow.com/a/11794507/5698182

yeah, look great.

**Comment by CaptainLiao** [comment]
I review the source code that `routeChunkNameRE` already validate name before `fileNameRE`.

**Pull request merged**
